# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1128, 837)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_menu = QtWidgets.QWidget(self.centralwidget)
        self.widget_menu.setObjectName("widget_menu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_menu)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.widget_menu)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pBtn_pve = QtWidgets.QPushButton(self.frame)
        self.pBtn_pve.setObjectName("pBtn_pve")
        self.verticalLayout_2.addWidget(self.pBtn_pve)
        self.widget_pve_para = QtWidgets.QWidget(self.frame)
        self.widget_pve_para.setEnabled(True)
        self.widget_pve_para.setObjectName("widget_pve_para")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_pve_para)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_pve_level = QtWidgets.QLabel(self.widget_pve_para)
        self.label_pve_level.setObjectName("label_pve_level")
        self.gridLayout_2.addWidget(self.label_pve_level, 0, 0, 1, 1)
        self.pBtn_pve_confirm = QtWidgets.QPushButton(self.widget_pve_para)
        self.pBtn_pve_confirm.setObjectName("pBtn_pve_confirm")
        self.gridLayout_2.addWidget(self.pBtn_pve_confirm, 3, 1, 1, 1)
        self.cb_pve_level = QtWidgets.QComboBox(self.widget_pve_para)
        self.cb_pve_level.setObjectName("cb_pve_level")
        self.cb_pve_level.addItem("")
        self.cb_pve_level.addItem("")
        self.cb_pve_level.addItem("")
        self.gridLayout_2.addWidget(self.cb_pve_level, 0, 1, 1, 1)
        self.label_pve_size = QtWidgets.QLabel(self.widget_pve_para)
        self.label_pve_size.setObjectName("label_pve_size")
        self.gridLayout_2.addWidget(self.label_pve_size, 1, 0, 1, 1)
        self.cb_pve_size = QtWidgets.QComboBox(self.widget_pve_para)
        self.cb_pve_size.setObjectName("cb_pve_size")
        self.cb_pve_size.addItem("")
        self.cb_pve_size.addItem("")
        self.cb_pve_size.addItem("")
        self.gridLayout_2.addWidget(self.cb_pve_size, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_pve_para)
        self.pBtn_watch = QtWidgets.QPushButton(self.frame)
        self.pBtn_watch.setObjectName("pBtn_watch")
        self.verticalLayout_2.addWidget(self.pBtn_watch)
        self.widget_watch_para = QtWidgets.QWidget(self.frame)
        self.widget_watch_para.setEnabled(True)
        self.widget_watch_para.setObjectName("widget_watch_para")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_watch_para)
        self.gridLayout.setObjectName("gridLayout")
        self.label_watch_level_w = QtWidgets.QLabel(self.widget_watch_para)
        self.label_watch_level_w.setObjectName("label_watch_level_w")
        self.gridLayout.addWidget(self.label_watch_level_w, 1, 0, 1, 1)
        self.cb_watch_level_w = QtWidgets.QComboBox(self.widget_watch_para)
        self.cb_watch_level_w.setObjectName("cb_watch_level_w")
        self.cb_watch_level_w.addItem("")
        self.cb_watch_level_w.addItem("")
        self.cb_watch_level_w.addItem("")
        self.gridLayout.addWidget(self.cb_watch_level_w, 1, 1, 1, 1)
        self.cb_watch_level_b = QtWidgets.QComboBox(self.widget_watch_para)
        self.cb_watch_level_b.setObjectName("cb_watch_level_b")
        self.cb_watch_level_b.addItem("")
        self.cb_watch_level_b.addItem("")
        self.cb_watch_level_b.addItem("")
        self.gridLayout.addWidget(self.cb_watch_level_b, 0, 1, 1, 1)
        self.pBtn_watch_confirm = QtWidgets.QPushButton(self.widget_watch_para)
        self.pBtn_watch_confirm.setObjectName("pBtn_watch_confirm")
        self.gridLayout.addWidget(self.pBtn_watch_confirm, 3, 1, 1, 1)
        self.label_watch_level_b = QtWidgets.QLabel(self.widget_watch_para)
        self.label_watch_level_b.setObjectName("label_watch_level_b")
        self.gridLayout.addWidget(self.label_watch_level_b, 0, 0, 1, 1)
        self.cb_watch_size = QtWidgets.QComboBox(self.widget_watch_para)
        self.cb_watch_size.setObjectName("cb_watch_size")
        self.cb_watch_size.addItem("")
        self.cb_watch_size.addItem("")
        self.cb_watch_size.addItem("")
        self.gridLayout.addWidget(self.cb_watch_size, 2, 1, 1, 1)
        self.label_watch_size = QtWidgets.QLabel(self.widget_watch_para)
        self.label_watch_size.setObjectName("label_watch_size")
        self.gridLayout.addWidget(self.label_watch_size, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_watch_para)
        self.pBtn_pvp = QtWidgets.QPushButton(self.frame)
        self.pBtn_pvp.setObjectName("pBtn_pvp")
        self.verticalLayout_2.addWidget(self.pBtn_pvp)
        self.widget_pvp_para = QtWidgets.QWidget(self.frame)
        self.widget_pvp_para.setEnabled(True)
        self.widget_pvp_para.setObjectName("widget_pvp_para")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_pvp_para)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_pvp_size = QtWidgets.QLabel(self.widget_pvp_para)
        self.label_pvp_size.setObjectName("label_pvp_size")
        self.gridLayout_3.addWidget(self.label_pvp_size, 0, 0, 1, 1)
        self.cb_pvp_size = QtWidgets.QComboBox(self.widget_pvp_para)
        self.cb_pvp_size.setObjectName("cb_pvp_size")
        self.cb_pvp_size.addItem("")
        self.gridLayout_3.addWidget(self.cb_pvp_size, 0, 1, 1, 1)
        self.pBtn_pvp_confirm = QtWidgets.QPushButton(self.widget_pvp_para)
        self.pBtn_pvp_confirm.setObjectName("pBtn_pvp_confirm")
        self.gridLayout_3.addWidget(self.pBtn_pvp_confirm, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_pvp_para)
        self.pBtn_quit = QtWidgets.QPushButton(self.frame)
        self.pBtn_quit.setObjectName("pBtn_quit")
        self.verticalLayout_2.addWidget(self.pBtn_quit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.widget_menu)
        self.widget_game = QtWidgets.QWidget(self.centralwidget)
        self.widget_game.setObjectName("widget_game")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_game)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_board = QtWidgets.QWidget(self.widget_game)
        self.widget_board.setObjectName("widget_board")
        self.horizontalLayout.addWidget(self.widget_board)
        self.cmd_pve = QtWidgets.QGroupBox(self.widget_game)
        self.cmd_pve.setObjectName("cmd_pve")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cmd_pve)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pBtn_undo = QtWidgets.QPushButton(self.cmd_pve)
        self.pBtn_undo.setObjectName("pBtn_undo")
        self.verticalLayout_3.addWidget(self.pBtn_undo)
        self.pBtn_pre = QtWidgets.QPushButton(self.cmd_pve)
        self.pBtn_pre.setObjectName("pBtn_pre")
        self.verticalLayout_3.addWidget(self.pBtn_pre)
        self.pBtn_next = QtWidgets.QPushButton(self.cmd_pve)
        self.pBtn_next.setObjectName("pBtn_next")
        self.verticalLayout_3.addWidget(self.pBtn_next)
        self.pBtn_tip = QtWidgets.QPushButton(self.cmd_pve)
        self.pBtn_tip.setObjectName("pBtn_tip")
        self.verticalLayout_3.addWidget(self.pBtn_tip)
        self.pBtn_surrender = QtWidgets.QPushButton(self.cmd_pve)
        self.pBtn_surrender.setObjectName("pBtn_surrender")
        self.verticalLayout_3.addWidget(self.pBtn_surrender)
        self.pBtn_back = QtWidgets.QPushButton(self.cmd_pve)
        self.pBtn_back.setObjectName("pBtn_back")
        self.verticalLayout_3.addWidget(self.pBtn_back)
        self.horizontalLayout.addWidget(self.cmd_pve)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.widget_game)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionabc = QtWidgets.QAction(MainWindow)
        self.actionabc.setObjectName("actionabc")
        self.actionPVP = QtWidgets.QAction(MainWindow)
        self.actionPVP.setObjectName("actionPVP")
        self.actionPVE = QtWidgets.QAction(MainWindow)
        self.actionPVE.setObjectName("actionPVE")
        self.menu.addSeparator()
        self.menu.addAction(self.actionPVP)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPVE)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pBtn_pve.setText(_translate("MainWindow", "开始一场对局"))
        self.label_pve_level.setText(_translate("MainWindow", "难度"))
        self.pBtn_pve_confirm.setText(_translate("MainWindow", "开始"))
        self.cb_pve_level.setItemText(0, _translate("MainWindow", "简单"))
        self.cb_pve_level.setItemText(1, _translate("MainWindow", "中等"))
        self.cb_pve_level.setItemText(2, _translate("MainWindow", "困难"))
        self.label_pve_size.setText(_translate("MainWindow", "棋盘大小"))
        self.cb_pve_size.setItemText(0, _translate("MainWindow", "15x15"))
        self.cb_pve_size.setItemText(1, _translate("MainWindow", "11x11"))
        self.cb_pve_size.setItemText(2, _translate("MainWindow", "8x8"))
        self.pBtn_watch.setText(_translate("MainWindow", "观看一场对局"))
        self.label_watch_level_w.setText(_translate("MainWindow", "白棋难度"))
        self.cb_watch_level_w.setItemText(0, _translate("MainWindow", "简单"))
        self.cb_watch_level_w.setItemText(1, _translate("MainWindow", "中等"))
        self.cb_watch_level_w.setItemText(2, _translate("MainWindow", "困难"))
        self.cb_watch_level_b.setItemText(0, _translate("MainWindow", "简单"))
        self.cb_watch_level_b.setItemText(1, _translate("MainWindow", "中等"))
        self.cb_watch_level_b.setItemText(2, _translate("MainWindow", "困难"))
        self.pBtn_watch_confirm.setText(_translate("MainWindow", "开始"))
        self.label_watch_level_b.setText(_translate("MainWindow", "黑棋难度"))
        self.cb_watch_size.setCurrentText(_translate("MainWindow", "15x15"))
        self.cb_watch_size.setItemText(0, _translate("MainWindow", "15x15"))
        self.cb_watch_size.setItemText(1, _translate("MainWindow", "11x11"))
        self.cb_watch_size.setItemText(2, _translate("MainWindow", "8x8"))
        self.label_watch_size.setText(_translate("MainWindow", "棋盘大小"))
        self.pBtn_pvp.setText(_translate("MainWindow", "与人类博弈"))
        self.label_pvp_size.setText(_translate("MainWindow", "棋盘大小"))
        self.cb_pvp_size.setItemText(0, _translate("MainWindow", "13x13"))
        self.pBtn_pvp_confirm.setText(_translate("MainWindow", "开始"))
        self.pBtn_quit.setText(_translate("MainWindow", "退出"))
        self.cmd_pve.setTitle(_translate("MainWindow", "控制"))
        self.pBtn_undo.setText(_translate("MainWindow", "悔棋"))
        self.pBtn_pre.setText(_translate("MainWindow", "上一步"))
        self.pBtn_next.setText(_translate("MainWindow", "下一步"))
        self.pBtn_tip.setText(_translate("MainWindow", "提示"))
        self.pBtn_surrender.setText(_translate("MainWindow", "认输"))
        self.pBtn_back.setText(_translate("MainWindow", "返回主菜单"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionabc.setText(_translate("MainWindow", "abc"))
        self.actionPVP.setText(_translate("MainWindow", "New PVP"))
        self.actionPVE.setText(_translate("MainWindow", "New PVE"))

